[package]
name = "zcutil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.27.0"
solana-program = "=1.14.17"
bytemuck = "1.4.0"
